[package]
name = "pyxis-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
pyxis = { path = "../" }
clap = { version = "4.5", features = ["derive"] }
anyhow = { workspace = true }

[[bin]]
name = "pyxis"
path = "src/main.rs"
